### PR TITLE
Adding the version to the Hub Project Name

### PR DESCRIPTION
**Pull request by imbeyondboredom**

### CODE REVIEW

**Comment by imbeyondboredom** [comment]
I believe this would address #25 because it would add the version to the project name - thus making it unique per version of the code you're scanning. This would not affect anything if the user manually sets the hub project name

**Comment by akamen** [comment]
@imbeyondboredom  Thanks for the PR, we will take a look immediately and get back to you.

**Comment by psantos1113** [comment]
I don't believe this will address the issue completely.  It may address the issue for android, but cause problems for customer's with group, artifact, and versions configured.  I have made a request for more information in issue #23

**Comment by imbeyondboredom** [comment]
I think you're right on this one. I think it needs to include the group here as well to ensure that it's unique.

Feel free to close and patch yourself or if you want me to add the group there then I can but I don't think I'll find time until next week.

**Comment by imbeyondboredom** [comment]
@psantos1113 If I change the line to this would you accept the PR?

`return getProject().getGroup()+":"+getProject().getName()+":"+getProject().getVersion();`

**Comment by imbeyondboredom** [comment]
@psantos1113 Why did you close this? This PR is irrelevant to #23. The issue is that the group/artifact/version are not taken into account with the new HUB. Here's a screenshot to prove it.

screen shot 2017-03-16 at 2 39 25 pm

**Pull request closed without merging**
